// <auto-generated />
namespace JBOFarmersMkt.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update20));
        
        string IMigrationMetadata.Id
        {
            get { return "201408151848480_update20"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
