// <auto-generated />
namespace JBOFarmersMkt.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update2));
        
        string IMigrationMetadata.Id
        {
            get { return "201408062056329_update2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
