// <auto-generated />
namespace JBOFarmersMkt.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class deleteUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201408241930036_deleteUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
