// <auto-generated />
namespace JBOFarmersMkt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class updateregistermodeltoincludecustomerattributes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateregistermodeltoincludecustomerattributes));
        
        string IMigrationMetadata.Id
        {
            get { return "201411081756079_update register model to include customer attributes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
