// <auto-generated />
namespace JBOFarmersMkt.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update24 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update24));
        
        string IMigrationMetadata.Id
        {
            get { return "201408211908564_update24"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
